services:
  search-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5273:80"
    environment:
      - INSTANCE=A
      - SQLITE_DB=/data/SearchDB-1.db
    volumes:
      - ./SearchData/SearchDB-1.db:/data/SearchDB-1.db:ro
