apiVersion: batch/v1
kind: CronJob
metadata:
  name: indexer-cronjob
  labels:
    app: indexer
spec:
  schedule: "*/2 * * * *"
  suspend: false
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 1200
      activeDeadlineSeconds: 600

      template:
        metadata:
          labels:
            app: indexer
        spec:
          restartPolicy: Never

          initContainers:
            - name: wait-for-rabbitmq
              image: busybox:1.36
              command:
                - sh
                - -c
                - |
                  echo "Waiting for rabbitmq:5672..."
                  until nc -z rabbitmq 5672; do
                    echo "RabbitMQ not ready yet..."
                    sleep 2
                  done
                  echo "RabbitMQ is up!"

            - name: wait-for-postgres
              image: busybox:1.36
              command:
                - sh
                - -c
                - |
                  echo "Waiting for postgres..."
                  until nc -z searchdb-postgresql.database.svc.cluster.local 5432; do
                    echo "Postgres not ready yet..."
                    sleep 2
                  done
                  echo "Postgres is up!"

          containers:
            - name: indexer
              image: fawad23/indexer:1.1.1
              imagePullPolicy: Always
              env:
                - name: INDEXER_DATABASE
                  value: "postgres"

                - name: INDEXER_FOLDER
                  value: "/data/small/compaq"

                - name: POSTGRES_CONNECTION
                  value: "Host=searchdb-postgresql.database.svc.cluster.local;Port=5432;Username=postgres;Password=1234;Database=SearchDB"

                - name: RABBITMQ_HOST
                  value: "rabbitmq"

                - name: RABBITMQ_PORT
                  value: "5672"

                - name: RABBITMQ_USER
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq-secret
                      key: RABBITMQ_DEFAULT_USER

                - name: RABBITMQ_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq-secret
                      key: RABBITMQ_DEFAULT_PASS

                - name: RABBITMQ_QUEUE
                  value: "indexer.events"

              volumeMounts:
                - name: seed-data
                  mountPath: /data
                  readOnly: true

          volumes:
            - name: seed-data
              hostPath:
                path: /mnt/seData
                type: Directory
