#########################################################
# Secrets
#########################################################
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
type: Opaque
data:
  password: Wk9uVU1SWkFtSg==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api
spec:
  selector:
    matchLabels:
      app: search-api
  replicas: 1
  template:
    metadata:
      labels:
        app: search-api
    spec:
      containers:
        - name: search-api
          image: fawad23/search-api:1.8.0
          env:
            - name: INSTANCE
              value: "A"
            - name: SQLITE_DB
              value: "/data/SearchDB-1.db"
            - name: RedisConnectionString
              value: "search-redis-master.caching.svc.cluster.local:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
          ports:
            - containerPort: 80
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: search-api
  labels:
    app: search-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "metrics"
spec:
  type: NodePort
  selector:
    app: search-api
  ports:
    - name: metrics
      port: 80
      targetPort: 80

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: search-api-monitor
  namespace: monitoring
  labels:
    app: search-api
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: search-api
  endpoints:
    - interval: 15s
      port: metrics
